### ISSUE TITLE
Import redefinition of protected methods

### ISSUE THREAD

**Issue by jrodriguez-rc** [larshp/abapGit#3053]
I have classes with redefined methods, when I try to import via abapGit to another system redefined methods doesn't appears.
Origin system:
![image](https://user-images.githubusercontent.com/56556686/68461432-81460680-020a-11ea-8dda-8afef3ecaa8b.png)

Destination system:
![image](https://user-images.githubusercontent.com/56556686/68461488-9d49a800-020a-11ea-8c5b-e819f3b58660.png)

But code is correctly executed:
![image](https://user-images.githubusercontent.com/56556686/68461547-c0745780-020a-11ea-8c60-bc65900e67fa.png)

**Comment by sbcgua** [comment]
+1 happens to me either

**Comment by filak-sap** [comment]
I hope it is no caused by the commit 4c3c4e8ea80434b8293b218e127e46513ba256ee
That commit enabled me to pull classes with redefinitions on our internal systems.

**Comment by Xylaw** [comment]
+1 same problem here

**Comment by christianguenter2** [comment]
works for me in NW 752 SP04

**Comment by larshp** [comment]
to those that can reproduce the problem: try reverting to the old code https://github.com/larshp/abapGit/commit/4c3c4e8ea80434b8293b218e127e46513ba256ee, and check to see if causes the error

Also please try to reduce the problem to as few objects as possible and put it in a public repo

**Comment by jrodriguez-rc** [comment]
> to those that can reproduce the problem: try reverting to the old code [4c3c4e8](https://github.com/larshp/abapGit/commit/4c3c4e8ea80434b8293b218e127e46513ba256ee), and check to see if causes the error
> 
> Also please try to reduce the problem to as few objects as possible and put it in a public repo

I tried reverting changes, but still have same problem.

I made this simple code to test it: https://gitlab.com/jrodriguez_rc/abagit-testing.git

It is just a root class and an inherit class with a single method redefined:
![image](https://user-images.githubusercontent.com/56556686/69072411-e0d2bc00-0a2b-11ea-9436-750309357b4c.png)

I compare original code with imported from git and is the same, but I found table SEOREDEF, redefinitions should be in that table but not.

If I create entry manually redefinition appears:
![image](https://user-images.githubusercontent.com/56556686/69072602-432bbc80-0a2c-11ea-9a73-e1f8b56ad782.png)

**Comment by larshp** [comment]
what version are you on, SAP_BASIS?

**Comment by jrodriguez-rc** [comment]
We are in 750 SP16

**Comment by Xylaw** [comment]
Our SAP_BASIS is 750 SP12

**Comment by christianguenter2** [comment]
I was able to reproduce the issue with the provided test repo. Interestingly the keyword `REDEFINITION` is in the code.
![image](https://user-images.githubusercontent.com/17437789/69653734-f2434600-1073-11ea-9402-23eed5862e46.png)

Activating with ADT or source code based SE24 fixed the issue. I suspect that there's is a subtle bug in the class activation logic.

**Comment by larshp** [comment]
experienced the same problem earlier today, 751

**Comment by larshp** [comment]
can someone try if this also happens if the redefinition is in the PUBLIC SECTION? or it only happens for PROTECTED SECTION?

**Comment by jfilak** [comment]
@christianguenter2 Did you reproduce it on ABAP Trial 752 SP04? We cannot reproduce the problem on our internal systems - development versions. However, we had a opposite problem (redefinitions counted twice) causing short dumps, but the commit https://github.com/larshp/abapGit/commit/4c3c4e8ea80434b8293b218e127e46513ba256ee  fixed it for us and now we can pull without any issue.

**Comment by larshp** [comment]
@jrodriguez-rc can you help removing the text stuff from the example? just keep it to the redefinition problem

**Comment by larshp** [comment]
reverting the change from https://github.com/larshp/abapGit/commit/4c3c4e8ea80434b8293b218e127e46513ba256ee and it seems to work as expected, the method is redefined properly

**Comment by jfilak** [comment]
@larshp OK, what are supposed to do now? Shall I just carry the patch in our local abapGit fork?

**Comment by larshp** [comment]
I'm thinking:

A: revert the code from https://github.com/larshp/abapGit/commit/4c3c4e8ea80434b8293b218e127e46513ba256ee
B: add a call to function module SEO_INHERITANC_REMOVE_REDEF to avoid the duplicate records

**Comment by jrodriguez-rc** [comment]
> @jrodriguez-rc can you help removing the text stuff from the example? just keep it to the redefinition problem

Removed texts

**Comment by jrodriguez-rc** [comment]
> can someone try if this also happens if the redefinition is in the PUBLIC SECTION? or it only happens for PROTECTED SECTION?

Happens only with protected methods
![image](https://user-images.githubusercontent.com/56556686/70066853-ae10f200-15ed-11ea-9bca-35dc63a2f4a9.png)

I updated test repository

**Comment by jfilak** [comment]
I reverted the mentioned patch and I managed to pull the example repo with some problems:
- the form class editor didn't know that the methods were redefined (runtime worked fine I've added a code to test runitme - https://gitlab.com/jfilak/abagit-testing)

@larshp Proposed to use SEO_INHERITANC_REMOVE_REDEF to do something. It is not clear to me what should I remove:
- everything related to the pulled class in the table seoredef? (then I would not insert the redefinitions with REFCLSNAME - see the commit message).
- or  lo_update->scan_result-redef_tab (context: zcl_abapgit_oo_class=>update_meta)? that's not possible because scan_result is read-only.

Anyways, I can still reproduce the short dump. The short dump occurs when I try to pull a class with protected redefinition and the class already exists in the system.

I am sad the patch causes you problems, but the simplest solution for us is to keep the patch - I have no problem to carry the patch as a downstream patch until you get the same AS ABAP as we do and you start suffering from the same problem - then you can spend time trying to find a different patch. I would say that the problem should be reproducible on ABAP 1908.

**Comment by larshp** [comment]
reverted, try https://github.com/larshp/abapGit/pull/3100

right now the error is silent and causes wrong behavior. Its better to have it show wrong in SE24(on higher stacks), and execute correct. The dump is bad, but it alerts the user that something is wrong.

lets keep this issue open, I would like to do some more testing, still not exactly sure which versions are affected

**Comment by schneider-michael** [comment]
See https://github.com/larshp/abapGit/pull/3122.
Not very elegant but it seems to work

**Comment by larshp** [comment]
fixed in https://github.com/larshp/abapGit/pull/3122
